language: ruby
dist: bionic
cache: bundler
services:
  - postgresql
  - elasticsearch
addons:
  postgresql: "9.4"
  chrome: stable
bundler_args: '--without development'
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/timeoverflow_test
    - CC_TEST_REPORTER_ID=025bc15a0fa9afa52d86ee24fea845cf1d363f48a466bcf2cef8ab80c29acb28
before_script:
  - psql -c 'create database timeoverflow_test;' -U postgres
  - bundle exec rails db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # allow elasticsearch to be ready - https://docs.travis-ci.com/user/database-setup/#ElasticSearch
  - sleep 10
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
